#!/usr/bin/env bash
# anvil/lib/fetch-secrets.sh — SSM Parameter Store → /etc/anvil/secrets.env
#
# §7.8 of the v3 doc. Runs as the anvil-secrets.service oneshot unit BEFORE
# the frankenphp units boot. Writes /etc/anvil/secrets.env (0600 root:anvil)
# containing EnvironmentFile-style KEY=value lines consumed by the
# anvil-frankenphp@.service template unit (EnvironmentFile=/etc/anvil/secrets.env).
#
# SSM paths consulted (all SecureString, all under /anvil/rds/*):
#   /anvil/rds/host       → DB_HOST
#   /anvil/rds/user       → DB_USER
#   /anvil/rds/password   → DB_PASSWORD
#   /anvil/rds/database   → DB_NAME
#
# Plus optional (skipped silently if absent):
#   /anvil/redis/host     → REDIS_HOST
#   /anvil/redis/password → REDIS_PASSWORD
#
# Exit codes:
#   0  — secrets.env written
#   1  — AWS CLI missing or AWS auth failed
#   2  — required SSM parameter missing
#
# When HUB-20 (Sovereign Vault) lands, replace the aws ssm calls with vault
# reads; the contract (write secrets.env with the same KEY= names) is unchanged.

set -euo pipefail

SECRETS_ENV="${ANVIL_SECRETS_ENV:-/etc/anvil/secrets.env}"
ANVIL_GROUP="${ANVIL_GROUP:-anvil}"

command -v aws >/dev/null 2>&1 || {
  echo "fetch-secrets: aws CLI not on PATH" >&2
  exit 1
}

# Required SSM paths → env var names.
declare -a REQUIRED_SSM=(
  "/anvil/rds/host:/anvil/rds/host"
  "/anvil/rds/user:/anvil/rds/user"
  "/anvil/rds/password:/anvil/rds/password"
  "/anvil/rds/database:/anvil/rds/database"
)
declare -a OPTIONAL_SSM=(
  "/anvil/redis/host"
  "/anvil/redis/password"
)

# Fetch a single SSM SecureString parameter. Prints its value (no trailing newline).
fetch_ssm() {
  local path="${1:?}"
  aws ssm get-parameter --with-decryption --name "$path" \
    --query 'Parameter.Value' --output text 2>/dev/null
}

# Build the EnvironmentFile body in memory, then write atomically.
TMP_BODY="$(mktemp)"
trap 'rm -f "$TMP_BODY"' EXIT

# Required — fail if any missing.
{
  echo "# /etc/anvil/secrets.env — generated by anvil/lib/fetch-secrets.sh at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "# DO NOT EDIT. Re-run 'systemctl restart anvil-secrets' to regenerate."
  echo
  echo "DB_HOST=$(fetch_ssm /anvil/rds/host)"
  echo "DB_USER=$(fetch_ssm /anvil/rds/user)"
  echo "DB_PASSWORD=$(fetch_ssm /anvil/rds/password)"
  echo "DB_NAME=$(fetch_ssm /anvil/rds/database)"
  echo "DB_DSN=mysql:host=\${DB_HOST};port=3306;dbname=\${DB_NAME}"
  echo
} >> "$TMP_BODY"

# Optional Redis path.
if redis_host="$(fetch_ssm /anvil/redis/host 2>/dev/null)" && [[ -n "$redis_host" ]]; then
  echo "REDIS_HOST=${redis_host}" >> "$TMP_BODY"
  if redis_pw="$(fetch_ssm /anvil/redis/password 2>/dev/null)" && [[ -n "$redis_pw" ]]; then
    echo "REDIS_PASSWORD=${redis_pw}" >> "$TMP_BODY"
    echo "REDIS_URL=redis://:\${REDIS_PASSWORD}@\${REDIS_HOST}:6379" >> "$TMP_BODY"
  else
    echo "REDIS_URL=redis://\${REDIS_HOST}:6379" >> "$TMP_BODY"
  fi
fi

# Atomic install + ownership/permissions.
install -d -m 0750 -o root -g "$ANVIL_GROUP" "$(dirname "$SECRETS_ENV")"
install -m 0640 -o root -g "$ANVIL_GROUP" "$TMP_BODY" "$SECRETS_ENV"
echo "fetch-secrets: wrote $SECRETS_ENV"
