#!/usr/bin/env bash
# anvil/lib/fetch-secrets.sh — SSM Parameter Store → /etc/anvil/secrets.env
#
# §7.8 of the v3 doc. Runs as the anvil-secrets.service oneshot unit BEFORE
# the frankenphp units boot. Writes /etc/anvil/secrets.env (0640 root:anvil)
# containing EnvironmentFile-style KEY=value lines consumed by the
# anvil-frankenphp@.service template unit (EnvironmentFile=/etc/anvil/secrets.env).
#
# SSM paths consulted (all SecureString, all under /anvil/rds/*):
#   /anvil/rds/host       → DB_HOST
#   /anvil/rds/user       → DB_USER
#   /anvil/rds/password   → DB_PASSWORD
#   /anvil/rds/database   → DB_NAME
#
# Plus optional (skipped silently if absent):
#   /anvil/redis/host     → REDIS_HOST
#   /anvil/redis/password → REDIS_PASSWORD
#
# Exit codes:
#   0  — secrets.env written (or a valid existing file was kept)
#   1  — AWS CLI missing or AWS auth failed AND no valid secrets.env
#   2  — required SSM parameter missing AND no valid secrets.env
#
# Local / first-boot: if AWS is unavailable but a dummy secrets.env already
# has the four required keys, succeed so frankenphp's Requires= does not fail.
# When HUB-20 (Sovereign Vault) lands, replace the aws ssm calls with vault
# reads; the contract (write secrets.env with the same KEY= names) is unchanged.

set -euo pipefail

SECRETS_ENV="${ANVIL_SECRETS_ENV:-/etc/anvil/secrets.env}"
ANVIL_GROUP="${ANVIL_GROUP:-anvil}"
SECRETS_DIR="$(dirname "$SECRETS_ENV")"

required_keys_present() {
  local f="${1:?}" k
  [[ -f "$f" ]] || return 1
  for k in DB_HOST DB_USER DB_PASSWORD DB_NAME; do
    grep -qE "^${k}=.+" "$f" || return 1
  done
  return 0
}

keep_existing() {
  local why="${1:?}"
  if required_keys_present "$SECRETS_ENV"; then
    echo "fetch-secrets: $why; keeping existing $SECRETS_ENV" >&2
    chmod 0640 "$SECRETS_ENV" 2>/dev/null || true
    chown "root:${ANVIL_GROUP}" "$SECRETS_ENV" 2>/dev/null || true
    exit 0
  fi
}

# Parent dir must stay world-traversable (0755) so caddy/tengine can read
# sibling configs under /etc/anvil/{edge,lb}. Do NOT chmod 0750 here.
install -d -m 0755 -o root -g root "$SECRETS_DIR"

if ! command -v aws >/dev/null 2>&1; then
  keep_existing "aws CLI not on PATH"
  echo "fetch-secrets: aws CLI not on PATH and no valid $SECRETS_ENV" >&2
  exit 1
fi

# Fetch a single SSM SecureString parameter. Prints its value (no trailing newline).
fetch_ssm() {
  local path="${1:?}" val
  if ! val="$(aws ssm get-parameter --with-decryption --name "$path" \
      --query 'Parameter.Value' --output text 2>/dev/null)"; then
    return 1
  fi
  [[ -n "$val" && "$val" != "None" ]] || return 1
  printf '%s' "$val"
}

db_host="" db_user="" db_password="" db_name=""
if ! db_host="$(fetch_ssm /anvil/rds/host)" \
   || ! db_user="$(fetch_ssm /anvil/rds/user)" \
   || ! db_password="$(fetch_ssm /anvil/rds/password)" \
   || ! db_name="$(fetch_ssm /anvil/rds/database)"; then
  keep_existing "SSM fetch failed"
  echo "fetch-secrets: required SSM parameter missing or empty" >&2
  exit 2
fi

# Build the EnvironmentFile body in memory, then write atomically.
TMP_BODY="$(mktemp)"
trap 'rm -f "$TMP_BODY"' EXIT

{
  echo "# /etc/anvil/secrets.env — generated by anvil/lib/fetch-secrets.sh at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  echo "# DO NOT EDIT. Re-run 'systemctl restart anvil-secrets' to regenerate."
  echo
  echo "DB_HOST=${db_host}"
  echo "DB_USER=${db_user}"
  echo "DB_PASSWORD=${db_password}"
  echo "DB_NAME=${db_name}"
  echo "DB_DSN=mysql:host=\${DB_HOST};port=3306;dbname=\${DB_NAME}"
  echo
} >> "$TMP_BODY"

# Optional Redis path.
if redis_host="$(fetch_ssm /anvil/redis/host 2>/dev/null || true)" && [[ -n "$redis_host" ]]; then
  echo "REDIS_HOST=${redis_host}" >> "$TMP_BODY"
  if redis_pw="$(fetch_ssm /anvil/redis/password 2>/dev/null || true)" && [[ -n "$redis_pw" ]]; then
    echo "REDIS_PASSWORD=${redis_pw}" >> "$TMP_BODY"
    echo "REDIS_URL=redis://:\${REDIS_PASSWORD}@\${REDIS_HOST}:6379" >> "$TMP_BODY"
  else
    echo "REDIS_URL=redis://\${REDIS_HOST}:6379" >> "$TMP_BODY"
  fi
fi

# Atomic install + ownership/permissions. File is 0640; directory stays 0755.
install -m 0640 -o root -g "$ANVIL_GROUP" "$TMP_BODY" "$SECRETS_ENV"
echo "fetch-secrets: wrote $SECRETS_ENV"
