#!/usr/bin/env bash
# shellcheck disable=SC1091
# anvil/lib/frankenphp.sh
#
# FrankenPHP app-tier lifecycle. Responsibilities:
#   * Generate blue/green Caddyfiles from the template (app/Caddyfile.blue),
#     with port + worker substitutions from anvil.conf (single source).
#   * install_units   — copy the systemd template into /etc/systemd/system.
#   * start / stop / status  — thin wrappers over `systemctl` (prod/staging)
#     or direct process management (dev collapsed mode, §5.5 of v3 doc).
#   * admin_status    — query the admin API (/frankenphp/threads, /metrics)
#     for live worker state. Used by `anvilctl status` and `anvilctl doctor`.
#
# Design notes:
#   * The blue and green Caddyfiles are byte-identical EXCEPT for the listen
#     port and admin port (§7.5 of v3 doc). Generating them from one template
#     guarantees that — manual edits drift.
#   * Secrets never live in the Caddyfile. They arrive via EnvironmentFile
#     (SSM-sourced) and are inherited by worker envs (§7.8 of v3 doc).
#   * In dev collapsed mode (§5.5), anvilctl uses dev/Caddyfile.dev directly
#     and skips the blue/green template entirely. This lib's `start`/`stop`
#     accept a `--dev` flag that switches to that path.

set -euo pipefail

if [[ -z "${ANVIL_ROOT:-}" ]]; then
  # shellcheck source=lib/core.sh
  source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/core.sh"
fi

# ---------------------------------------------------------------------------
# Template generation (blue/green)
# ---------------------------------------------------------------------------

# anvil_frankenphp_render TEMPLATE_OUT  [blue|green]
#   Renders $ANVIL_ROOT/app/Caddyfile.blue → $1 with port + admin substitutions
#   for the requested pool. The blue template is the canonical source; the
#   green variant is generated by swapping the two port vars.
anvil_frankenphp_render() {
  local out="${1:?Usage: anvil_frankenphp_render OUT [blue|green]}"
  local pool="${2:-blue}"
  local template="${ANVIL_ROOT}/app/Caddyfile.blue"
  [[ -f "$template" ]] || anvil_die 2 "missing template: $template (run install.sh?)"

  local listen_port admin_port root_dir
  case "$pool" in
    blue)  listen_port="$FRANKENPHP_BLUE_PORT";  admin_port="$FRANKENPHP_BLUE_ADMIN_PORT" ;;
    green) listen_port="$FRANKENPHP_GREEN_PORT"; admin_port="$FRANKENPHP_GREEN_ADMIN_PORT" ;;
    *) anvil_die 2 "anvil_frankenphp_render: pool must be blue|green (got '$pool')" ;;
  esac

  # Worker count: prefer explicit ANVIL_WORKERS; else env-specific defaults.
  local workers="${ANVIL_WORKERS:-}"
  if [[ -z "$workers" ]]; then
    case "$ANVIL_ENV" in
      dev)       workers="$ANVIL_DEV_WORKERS" ;;
      staging)   workers="$ANVIL_STAGING_WORKERS" ;;
      production)
        # 2*vCPU (floor 2). nproc is universally available on Linux.
        if command -v nproc >/dev/null 2>&1; then
          local cpu; cpu="$(nproc)"; workers=$(( cpu * 2 ))
          (( workers < 2 )) && workers=2
        else
          workers=2
        fi
        ;;
      *) workers=2 ;;
    esac
  fi

  # The release root: prod/staging = /opt/anvil/current(-green); dev = ANVIL_ROOT/..
  # (the repo root, where public/index.php lives per ADR-016 layout).
  case "$ANVIL_ENV" in
    dev) root_dir="${ANVIL_ROOT}/.." ;;
    *)   case "$pool" in
           blue)  root_dir="${ANVIL_CURRENT_SYMLINK}" ;;
           green) root_dir="${ANVIL_CURRENT_GREEN_SYMLINK}" ;;
         esac ;;
  esac

  # Substitute the template tokens. The template uses literal placeholders
  # so a stray `sed -E` in the Caddyfile doesn't get expanded.
  mkdir -p "$(dirname "$out")"
  sed -e "s|__LISTEN_PORT__|${listen_port}|g" \
      -e "s|__ADMIN_PORT__|${admin_port}|g" \
      -e "s|__WORKERS__|${workers}|g" \
      -e "s|__APP_ROOT__|${root_dir}|g" \
      -e "s|__TRUSTED_PROXIES__|${TRUSTED_PROXIES}|g" \
      -e "s|__APP_ENV__|${ANVIL_ENV}|g" \
      "$template" > "$out"
  anvil_debug "rendered $pool → $out (listen=$listen_port admin=$admin_port workers=$workers root=$root_dir)"
}

# anvil_frankenphp_install_configs
#   Renders blue AND green Caddyfiles to /etc/anvil/app/ (creating the dir).
#   Used by install.sh and `anvilctl provision`. Idempotent.
anvil_frankenphp_install_configs() {
  [[ $EUID -eq 0 ]] || anvil_die 1 "anvil_frankenphp_install_configs requires root (use sudo)"
  local target_dir
  target_dir="$(dirname "$ANVIL_APP_CADDYFILE_BLUE")"
  mkdir -p "$target_dir"
  anvil_frankenphp_render "$ANVIL_APP_CADDYFILE_BLUE"  blue
  anvil_frankenphp_render "$ANVIL_APP_CADDYFILE_GREEN" green
  chmod 0644 "$ANVIL_APP_CADDYFILE_BLUE" "$ANVIL_APP_CADDYFILE_GREEN"
  anvil_info "frankenphp configs installed: $target_dir/Caddyfile.{blue,green}"
}

# ---------------------------------------------------------------------------
# Lifecycle
# ---------------------------------------------------------------------------

# anvil_frankenphp_start [blue|green]   — prod/staging path (systemd unit)
# anvil_frankenphp_start dev            — collapsed mode (foreground process)
anvil_frankenphp_start() {
  local pool="${1:-blue}"
  case "$pool" in
    dev)
      anvil_require "$ANVIL_FRANKENPHP_BIN"
      local cfg="${ANVIL_ROOT}/dev/Caddyfile.dev"
      [[ -f "$cfg" ]] || anvil_die 2 "missing dev Caddyfile: $cfg"
      anvil_info "starting frankenphp dev (collapsed mode) — $cfg"
      exec "$ANVIL_FRANKENPHP_BIN" run --config "$cfg"
      ;;
    blue|green)
      # Prod/staging: delegate to systemd. Requires the template unit installed.
      [[ -f /etc/systemd/system/anvil-frankenphp@.service ]] \
        || anvil_die 2 "missing systemd template; run 'anvilctl provision install-units' first"
      systemctl start "anvil-frankenphp@${pool}"
      anvil_info "started anvil-frankenphp@${pool}"
      ;;
    *) anvil_die 2 "anvil_frankenphp_start: pool must be dev|blue|green" ;;
  esac
}

# anvil_frankenphp_stop [blue|green|dev]
anvil_frankenphp_stop() {
  local pool="${1:-blue}"
  case "$pool" in
    dev)
      # Collapsed mode runs in the foreground (exec'd by anvilctl start).
      # Stopping = SIGTERM the foreground process. anvilctl handles that.
      anvil_info "frankenphp dev stop: send SIGTERM to the foreground process"
      ;;
    blue|green)
      systemctl stop "anvil-frankenphp@${pool}" 2>/dev/null || true
      anvil_info "stopped anvil-frankenphp@${pool}"
      ;;
    *) anvil_die 2 "anvil_frankenphp_stop: pool must be dev|blue|green" ;;
  esac
}

# anvil_frankenphp_status [blue|green|dev]  — prints state + worker counts.
anvil_frankenphp_status() {
  local pool="${1:-blue}"
  case "$pool" in
    dev)
      local admin="127.0.0.1:2019"   # dev uses the standard admin port
      if curl -fsS "http://${admin}/frankenphp/threads" >/dev/null 2>&1; then
        echo "frankenphp[dev]: up (admin=$admin)"
        anvil_frankenphp_admin_status "$admin"
      else
        echo "frankenphp[dev]: down"
      fi
      ;;
    blue|green)
      local admin_port
      case "$pool" in
        blue)  admin_port="$FRANKENPHP_BLUE_ADMIN_PORT" ;;
        green) admin_port="$FRANKENPHP_GREEN_ADMIN_PORT" ;;
      esac
      local admin="127.0.0.1:${admin_port}"
      if systemctl is-active --quiet "anvil-frankenphp@${pool}"; then
        echo "frankenphp[${pool}]: active (admin=$admin)"
        anvil_frankenphp_admin_status "$admin"
      else
        echo "frankenphp[${pool}]: inactive"
      fi
      ;;
    *) anvil_die 2 "anvil_frankenphp_status: pool must be dev|blue|green" ;;
  esac
}

# anvil_frankenphp_admin_status ADMIN_ADDR
#   Queries /frankenphp/threads and /metrics on the admin API. Pretty-prints.
anvil_frankenphp_admin_status() {
  local admin="${1:?}"
  anvil_require curl jq
  local threads
  if threads="$(curl -fsS "http://${admin}/frankenphp/threads" 2>/dev/null)"; then
    local total busy idle
    total="$(jq 'length' <<< "$threads" 2>/dev/null || echo "?")"
    busy="$(jq '[.[] | select(.state=="busy")] | length' <<< "$threads" 2>/dev/null || echo "?")"
    idle="$(jq '[.[] | select(.state=="idle")] | length' <<< "$threads" 2>/dev/null || echo "?")"
    echo "  threads: total=${total} busy=${busy} idle=${idle}"
  else
    echo "  threads: admin API unreachable"
  fi
  # Prometheus metrics — surface the two Anvil cares about.
  local metrics
  if metrics="$(curl -fsS "http://${admin}/metrics" 2>/dev/null)"; then
    local total_threads busy_threads
    total_threads="$(awk '/^frankenphp_total_threads/ {print $2}' <<< "$metrics" | head -1)"
    busy_threads="$(awk '/^frankenphp_busy_threads/ {print $2}' <<< "$metrics" | head -1)"
    [[ -n "$total_threads" ]] && echo "  metrics: total_threads=${total_threads} busy_threads=${busy_threads}"
  fi
}

# ---------------------------------------------------------------------------
# Doctor hook — verifies admin-API reachability for anvilctl doctor.
# ---------------------------------------------------------------------------

# anvil_frankenphp_doctor  — exit 0 if the active pool's admin responds.
# Called from anvilctl doctor AFTER the version-floor check (lib/core.sh).
anvil_frankenphp_doctor() {
  local admin_port
  case "${ANVIL_ENV:-dev}" in
    dev)      admin_port=2019 ;;  # dev collapsed mode uses 2019
    staging|production) admin_port="$FRANKENPHP_BLUE_ADMIN_PORT" ;;
  esac
  local admin="127.0.0.1:${admin_port}"
  if curl -fsS "http://${admin}/health" >/dev/null 2>&1; then
    anvil_info "OK    frankenphp admin reachable at $admin"
    return 0
  fi
  anvil_warn "MISS  frankenphp admin not reachable at $admin (process down?)"
  return 0   # advisory — version floor is the hard gate, not liveness
}
