<?php

namespace DGLab\Services\Superpowers\Lexer;

/**
 * Class Lexer
 *
 * Scans .super.php files and produces a stream of tokens.
 */
class Lexer
{
    /**
     * Regex patterns for token identification.
     */
    private const PATTERN_SETUP = '/^~setup\s*\{(.*?)\}/s';
    private const PATTERN_MOUNT = '/^~mount\s*\{(.*?)\}/s';
    private const PATTERN_RENDERED = '/^~rendered\s*\{(.*?)\}/s';
    private const PATTERN_CLEANUP = '/^~cleanup\s*\{(.*?)\}/s';
    private const PATTERN_DIRECTIVE = '/^(@[a-zA-Z0-9]+(?:\s*(\((?:[^()]++|(?2))*\)))?)/s';
    private const PATTERN_EXPRESSION_RAW = '/^\{!!\s*(.*?)\s*!!\}/s';
    private const PATTERN_EXPRESSION_ESCAPED = '/^\{\{\s*(.*?)\s*\}\}/s';
    private const PATTERN_COMPONENT_SELF_CLOSING = '/^<s:([a-zA-Z0-9\-\.\:]+)\s*([^>]*?)\s*\/>/s';
    private const PATTERN_COMPONENT_OPEN = '/^<s:([a-zA-Z0-9\-\.\:]+)\s*([^>]*?)>/s';
    private const PATTERN_COMPONENT_CLOSE = '/^<\/s:([a-zA-Z0-9\-\.\:]+)\s*>/s';
    // Match any HTML tag with a reactive or special s- attribute: <button @click="..." s-loading>
    private const PATTERN_REACTIVE_TAG = '/^<([a-zA-Z0-9]+)\s+[^>]*?(@[a-zA-Z0-9]+|s-[a-z\.]+)=[^>]*?>/s';

    /**
     * Tokens generated by the Lexer.
     *
     * @var Token[]
     */
    private array $tokens = [];

    /**
     * The input content to be tokenized.
     */
    private string $input;

    /**
     * Current line number for error reporting.
     */
    private int $line = 1;

    /**
     * Tokenize the input content.
     */
    public function tokenize(string $content): array
    {
        $this->input = $content;
        $this->tokens = [];
        $this->line = 1;

        while ($this->input !== '') {
            if ($this->matchLifecycle()) continue;
            if ($this->matchExpressionRaw()) continue;
            if ($this->matchExpressionEscaped()) continue;
            if ($this->matchDirective()) continue;
            if ($this->matchComponentSelfClosing()) continue;
            if ($this->matchComponentOpen()) continue;
            if ($this->matchComponentClose()) continue;
            if ($this->matchReactiveTag()) continue;

            $this->matchText();
        }

        return $this->tokens;
    }

    private function matchLifecycle(): bool
    {
        if (preg_match(self::PATTERN_SETUP, $this->input, $matches)) {
            $this->pushToken(Token::T_SETUP_BLOCK, $matches[1]);
            $this->consume($matches[0]);
            return true;
        }
        if (preg_match(self::PATTERN_MOUNT, $this->input, $matches)) {
            $this->pushToken(Token::T_MOUNT_BLOCK, $matches[1]);
            $this->consume($matches[0]);
            return true;
        }
        if (preg_match(self::PATTERN_RENDERED, $this->input, $matches)) {
            $this->pushToken(Token::T_RENDERED_BLOCK, $matches[1]);
            $this->consume($matches[0]);
            return true;
        }
        if (preg_match(self::PATTERN_CLEANUP, $this->input, $matches)) {
            $this->pushToken(Token::T_CLEANUP_BLOCK, $matches[1]);
            $this->consume($matches[0]);
            return true;
        }
        return false;
    }

    private function matchExpressionRaw(): bool
    {
        if (preg_match(self::PATTERN_EXPRESSION_RAW, $this->input, $matches)) {
            $this->pushToken(Token::T_EXPRESSION_RAW, $matches[1]);
            $this->consume($matches[0]);
            return true;
        }
        return false;
    }

    private function matchExpressionEscaped(): bool
    {
        if (preg_match(self::PATTERN_EXPRESSION_ESCAPED, $this->input, $matches)) {
            $this->pushToken(Token::T_EXPRESSION_ESCAPED, $matches[1]);
            $this->consume($matches[0]);
            return true;
        }
        return false;
    }

    private function matchDirective(): bool
    {
        if (preg_match(self::PATTERN_DIRECTIVE, $this->input, $matches)) {
            $this->pushToken(Token::T_DIRECTIVE, $matches[1]);
            $this->consume($matches[0]);
            return true;
        }
        return false;
    }

    private function matchComponentSelfClosing(): bool
    {
        if (preg_match(self::PATTERN_COMPONENT_SELF_CLOSING, $this->input, $matches)) {
            $this->pushToken(Token::T_COMPONENT_SELF_CLOSING, $matches[0]);
            $this->consume($matches[0]);
            return true;
        }
        return false;
    }

    private function matchComponentOpen(): bool
    {
        if (preg_match(self::PATTERN_COMPONENT_OPEN, $this->input, $matches)) {
            $this->pushToken(Token::T_COMPONENT_OPEN, $matches[0]);
            $this->consume($matches[0]);
            return true;
        }
        return false;
    }

    private function matchComponentClose(): bool
    {
        if (preg_match(self::PATTERN_COMPONENT_CLOSE, $this->input, $matches)) {
            $this->pushToken(Token::T_COMPONENT_CLOSE, $matches[0]);
            $this->consume($matches[0]);
            return true;
        }
        return false;
    }

    private function matchReactiveTag(): bool
    {
        if (preg_match(self::PATTERN_REACTIVE_TAG, $this->input, $matches)) {
            $this->pushToken(Token::T_REACTIVE_TAG, $matches[0]);
            $this->consume($matches[0]);
            return true;
        }
        return false;
    }

    private function matchText(): void
    {
        $specials = ['~setup', '~mount', '~rendered', '~cleanup', '{{', '{!!', '<s:', '</s:', '@'];
        $closestPos = strlen($this->input);

        foreach ($specials as $special) {
            $pos = strpos($this->input, $special);
            if ($pos !== false && $pos < $closestPos) {
                if ($special === '@') {
                    $remaining = substr($this->input, $pos);
                    if (preg_match(self::PATTERN_DIRECTIVE, $remaining)) {
                        $closestPos = $pos;
                    }
                } else {
                    $closestPos = $pos;
                }
            }
        }

        $reactivePos = strpos($this->input, '<');
        if ($reactivePos !== false && $reactivePos < $closestPos) {
             $remaining = substr($this->input, $reactivePos);
             if (preg_match(self::PATTERN_REACTIVE_TAG, $remaining)) {
                  $closestPos = $reactivePos;
             }
        }

        if ($closestPos > 0) {
            $text = substr($this->input, 0, $closestPos);
            $this->pushToken(Token::T_TEXT, $text);
            $this->consume($text);
        } else if ($closestPos === 0 && $this->input !== '') {
            $char = $this->input[0];
            $this->pushToken(Token::T_TEXT, $char);
            $this->consume($char);
        }
    }

    private function consume(string $text): void
    {
        $this->line += substr_count($text, "\n");
        $this->input = substr($this->input, strlen($text));
    }

    private function pushToken(string $type, string $value): void
    {
        $this->tokens[] = new Token($type, $value, $this->line);
    }
}
