name: CI and Deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, gd
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPCS
      run: composer run cs

    - name: Run PHPStan
      run: composer run analyse

    - name: Run Tests
      run: composer run test

    - name: Install production dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          .env
          .env.example
          phpunit.xml
          DGLab.zip
          LICENSE
          README.md
          .gitignore
          .github/**
          docs/**
          cli/**
          composer.json
          composer.lock
          CI.log
          AGENTS.md
